export const movies = [
  {
    id: 533535,
    title: "Deadpool & Wolverine",
    release_date: "2024-07-24",
    backdrop_path: "https://image.tmdb.org/t/p/original/YDHyTFA3R9jFYba16jBB1ef8oIt.jpg",
    poster_path: "https://tse1.mm.bing.net/th/id/OIP.sb72e0DVYLAnjAK5n3JsZwHaK9?rs=1&pid=ImgDetMain&o=7&rm=3",
    category: "Action",
  },
  {
    id: 718821,
    title: "Twisters",
    release_date: "2024-07-10",
    backdrop_path: "https://image.tmdb.org/t/p/original/58D6ZAvv0xk1HJyX9S8qNkSBE9Y.jpg",
    poster_path: "https://tse3.mm.bing.net/th/id/OIP.tASFdbvdo6HY0oYh8ySfHQHaK-?rs=1&pid=ImgDetMain&o=7&rm=3",
    category: "Thriller",
  },
  {
    id: 1022789,
    title: "Inside Out 2",
    release_date: "2024-06-11",
    backdrop_path: "https://image.tmdb.org/t/p/original/fg2h6P1sZd1O1QdLNh4pD1sZw1.jpg",
    poster_path: "https://tse3.mm.bing.net/th/id/OIP.epjFJueo-VyGiI7iM_P7OQHaLG?rs=1&pid=ImgDetMain&o=7&rm=3",
    category: "Animation",
  },
  {
    id: 539543,
    title: "Despicable Me 4",
    release_date: "2024-06-20",
    backdrop_path: "https://image.tmdb.org/t/p/original/LgkpzCOSnTvjeMnuFzozRO5HHw1.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/dbtxg1bQYYuWMQvtEuoiUe4uvFJ.jpg",
    category: "Animation",
  },
  {
    id: 573435,
    title: "Bad Boys: Ride or Die",
    release_date: "2024-06-05",
    backdrop_path: "https://image.tmdb.org/t/p/original/3gQ1ACG0vMmDekhvkFPCXyPZSu.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/oGythE98MYleE6mZlGs5oBGkux1.jpg",
    category: "Action",
  },
  {
    id: 1106081,
    title: "Kill",
    release_date: "2024-07-03",
    backdrop_path: "https://image.tmdb.org/t/p/original/okLvML5y18dFN2Ru4mfZGEaCEd.jpg",
    poster_path: "https://images.plex.tv/photo?size=large-720&scale=2&url=https:%2F%2Fimage.tmdb.org%2Ft%2Fp%2Foriginal%2Ft56aRhrQgvvXOPhC1xh5E3c2GWW.jpg",
    category: "Action",
  },
  {
    id: 762441,
    title: "A Quiet Place: Day One",
    release_date: "2024-06-26",
    backdrop_path: "https://image.tmdb.org/t/p/original/2RVCJbWFmICRDsVxr1i8F5xkmRSk.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/vbI5h1Enc3gscdmg7lRnG4jX4R7.jpg",
    category: "Horror",
  },
  {
    id: 838115,
    title: "Saving Bikini Bottom: The Sandy Cheeks Movie",
    release_date: "2024-08-21",
    backdrop_path: "https://image.tmdb.org/t/p/original/hdfIDxWSBFSNZwSuotJwImshIQ.jpg",
    poster_path: "https://artworks.thetvdb.com/banners/v4/movie/346012/posters/65af3eed9a154.jpg",
    category: "Animation",
  },
  {
    id: 1079091,
    title: "It Ends with Us",
    release_date: "2024-08-07",
    backdrop_path: "https://image.tmdb.org/t/p/original/8yPSYhooJ8nyBbmV3GVdLDwuE7e.jpg",
    poster_path: "https://s3.amazonaws.com/nightjarprod/content/uploads/sites/261/2024/07/17125931/cSMdFWmajaX4oUMLx7HEDI84GkP-scaled.jpg",
    category: "Drama",
  },
  {
    id: 945961,
    title: "Alien: Romulus",
    release_date: "2024-08-13",
    backdrop_path: "https://image.tmdb.org/t/p/original/95SEurSqhJjBMzRea4BTh17rUac.jpg",
    poster_path: "https://tse1.mm.bing.net/th/id/OIP.zSM9U3ZUO6WZb8e31cGOrgHaK-?rs=1&pid=ImgDetMain&o=7&rm=3",
    category: "Sci-Fi",
  },
  // Extra Movies
  {
    id: 601,
    title: "The Matrix",
    release_date: "1999-03-31",
    backdrop_path: "https://image.tmdb.org/t/p/original/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/aOIuZAjPaRIE6CMzbazvcHuHXDc.jpg",
    category: "Sci-Fi",
  },
  {
    id: 155,
    title: "The Dark Knight",
    release_date: "2008-07-18",
    backdrop_path: "https://image.tmdb.org/t/p/original/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    category: "Action",
  },
  {
    id: 27205,
    title: "Inception",
    release_date: "2010-07-16",
    backdrop_path: "https://image.tmdb.org/t/p/original/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg",
    category: "Sci-Fi",
  },
  {
    id: 420818,
    title: "The Lion King",
    release_date: "2019-07-12",
    backdrop_path: "https://image.tmdb.org/t/p/original/2bXbqYdUdNVa8VIWXVfclP2ICtT.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg",
    category: "Animation",
  },
  {
    id: 597,
    title: "Titanic",
    release_date: "1997-12-19",
    backdrop_path: "https://image.tmdb.org/t/p/original/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    category: "Drama",
  },
  {
    id: 550,
    title: "Fight Club",
    release_date: "1999-10-15",
    backdrop_path: "https://image.tmdb.org/t/p/original/rr7E0NoGKxvbkb89eR1GwfoYjpA.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg",
    category: "Thriller",
  },
  {
    id: 680,
    title: "Pulp Fiction",
    release_date: "1994-09-10",
    backdrop_path: "https://image.tmdb.org/t/p/original/9rZg1J6vMQoDVSgRyWcpJa8IAGy.jpg",
    poster_path: "https://tse2.mm.bing.net/th/id/OIP.G0KtSmA4raGN5qxJMa-dSgHaLH?w=1200&h=1800&rs=1&pid=ImgDetMain&o=7&rm=3",
    category: "Thriller",
  },
  {
    id: 299534,
    title: "Avengers: Endgame",
    release_date: "2019-04-24",
    backdrop_path: "https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    category: "Action",
  },
  {
    id: 24428,
    title: "The Avengers",
    release_date: "2012-04-25",
    backdrop_path: "https://image.tmdb.org/t/p/original/hbn46fQaRmlpBuUrEiFqv0GDL6Y.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
    category: "Action",
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    release_date: "2022-12-07",
    backdrop_path: "https://image.tmdb.org/t/p/original/kALXyW4RmndtWH4jD9iDjlwVbQH.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    category: "Animation",
  },
];
